-- PREGUNTA 1
SELECT UPPER(NOMBRE||' '||APE_PATERNO||' '||APE_MATERNO)AS NOMBRE_COMPLETO,
        FECHA_FIN_CONTRATO
FROM EMPLEADO
WHERE ACTIVO LIKE 'S' AND FECHA_FIN_CONTRATO<ADD_MONTHS(SYSDATE,+6)
ORDER BY FECHA_FIN_CONTRATO DESC;

-- PREGUNTA 2
SELECT ID_ORDEN_PRODUCCION,FECHA_CULMINACION,
        ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_CULMINACION),2) CANTIDAD_MESES
FROM ORDEN_PRODUCCION
WHERE EXTRACT(MONTH FROM FECHA_CULMINACION)<=6 AND EXTRACT(YEAR FROM FECHA_CULMINACION)=2024
ORDER BY 1;

-- PREGUNTA 3
SELECT D.ARTICULO,MIN(D.CANTIDAD) MINIMO,MAX(D.CANTIDAD) MAXIMO
FROM DETALLE_ORD_PRODUCCION D,ORDEN_PRODUCCION P
WHERE D.ID_ORDEN_PRODUCCION=P.ID_ORDEN_PRODUCCION
GROUP BY D.ARTICULO;

-- PREGUNTA 4
SELECT S.ID_SEDE,S.NOMBRE_SEDE,COUNT(*)
FROM SEDE S,ORDEN_PEDIDO O
WHERE S.ID_SEDE=O.ID_SEDE AND EXTRACT(YEAR FROM FECHA_ENTREGA)=2024
GROUP BY S.ID_SEDE,S.NOMBRE_SEDE;

-- PREGUNTA 5
SELECT C.ID_CLIENTE,C.RAZON_SOCIAL
FROM CLIENTE C,ORDEN_PEDIDO OP,DETALLE_ORD_PEDIDO DOP,TIPO_BUS B
WHERE C.ID_CLIENTE=OP.ID_CLIENTE AND OP.ID_ORDEN_PEDIDO=DOP.ID_ORDEN_PEDIDO
        AND DOP.ID_TIPO_BUS=B.ID_TIPO_BUS AND B.ID_TIPO_BUS IN (1,2)
GROUP BY C.ID_CLIENTE,C.RAZON_SOCIAL;

-- PREGUNTA 6
SELECT B.NOMBRE,SUM(DOP.CANTIDAD) CANTIDAD
FROM CLIENTE C,DETALLE_ORD_PEDIDO DOP,TIPO_BUS B,ORDEN_PEDIDO OP
WHERE C.ID_CLIENTE=OP.ID_CLIENTE AND OP.ID_ORDEN_PEDIDO=DOP.ID_ORDEN_PEDIDO
        AND DOP.ID_TIPO_BUS=B.ID_TIPO_BUS
GROUP BY B.NOMBRE
HAVING SUM(DOP.CANTIDAD)>40;

-- PREGUNTA 7
SELECT F.NOMBRE_FORMA_PAGO, SUM(DOP.CANTIDAD) CANTIDAD
FROM FORMA_PAGO F,ORDEN_PEDIDO OP,DETALLE_ORD_PEDIDO DOP,CLIENTE C
WHERE F.ID_FORMA_PAGO=OP.ID_FORMA_PAGO AND OP.ID_ORDEN_PEDIDO=DOP.ID_ORDEN_PEDIDO
        AND C.ID_CLIENTE=OP.ID_CLIENTE
GROUP BY F.NOMBRE_FORMA_PAGO;


