-- NOMBRE: Ariana Burga
-- CÓDIGO: 20226705

-- Pregunta 1
CREATE TABLE EMPLEADO (
    ID_EMPLEADO NUMBER NOT NULL,
    NOMBRE VARCHAR2(40) NULL,
    APE_PATERNO VARCHAR2(40) NULL,
    APE_MATERNO VARCHAR2(40) NULL,
    ACTIVO CHAR(1) NULL,
    CONSTRAINT PK_ID_EMPLEADO PRIMARY KEY (ID_EMPLEADO)
);

-- Pregunta 2
COMMENT ON COLUMN EMPLEADO.ID_EMPLEADO IS 'Identificador de empleado';
COMMENT ON COLUMN EMPLEADO.NOMBRE IS 'Nombre del empleado';
COMMENT ON COLUMN EMPLEADO.APE_PATERNO IS 'Apellido paterno del empleado';
COMMENT ON COLUMN EMPLEADO.APE_MATERNO IS 'Apellido materno del empleado';
COMMENT ON COLUMN EMPLEADO.ACTIVO IS 'Indicador si el empleado esta activo o no: Si (S) o No (N)';

-- Pregunta 3
CREATE TABLE ROL (
    ID_ROL NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(50) NOT NULL,
    ES_JEFE CHAR(1) NOT NULL,
    CONSTRAINT PK_ID_ROL PRIMARY KEY (ID_ROL)
);

-- Pregunta 4
COMMENT ON COLUMN ROL.ID_ROL IS 'Identificador del rol';
COMMENT ON COLUMN ROL.DESCRIPCION IS 'Descripción del rol';
COMMENT ON COLUMN ROL.ES_JEFE IS 'Identificador de si el rol es jefe: Si (S) o No (N)';

-- Pregunta 5
ALTER TABLE EMPLEADO
ADD FECHA_FIN_CONTRATO DATE NOT NULL;

ALTER TABLE EMPLEADO
ADD IDROL NUMBER NOT NULL;

ALTER TABLE ROL
ADD ACTIVO CHAR(1 BYTE) NOT NULL;
COMMENT ON COLUMN ROL.ACTIVO IS 'Identificador de si el rol está activo: Si (S) o No (N)';

ALTER TABLE CLIENTE
ADD ACTIVO CHAR(1 BYTE) NULL;
COMMENT ON COLUMN CLIENTE.ACTIVO IS 'Identificador de si el cliente está activo: Si (S) o No (N)';

ALTER TABLE SEDE
ADD CODIGO_POSTAL VARCHAR2(6 BYTE) NULL;

ALTER TABLE SEDE
ADD ACTIVO CHAR(1 BYTE) NULL;
COMMENT ON COLUMN SEDE.ACTIVO IS 'Identificador de si la sede está activa: Si (S) o No (N)';

-- Pregunta 6
ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_IDROL FOREIGN KEY (IDROL) REFERENCES ROL(ID_ROL);

-- Pregunta 7
ALTER TABLE CLIENTE
MODIFY RAZON_SOCIAL VARCHAR2(80 BYTE);

ALTER TABLE CLIENTE
MODIFY DIRECCION_FISCAL VARCHAR2(120 BYTE);

-- Pregunta 8
ALTER TABLE FORMAPAGO
RENAME COLUMN NOMBRE TO NOMBRE_FORMA_PAGO;

ALTER TABLE SEDE
RENAME COLUMN AREA TO AREA_SEDE;

-- Pregunta 9
SELECT NOMBRESEDE,DISTRITO
FROM SEDE
WHERE PROVINCIA='Lima' AND DISTRITO IN ('Lurin','Villa El Salvador');

-- Pregunta 10
INSERT INTO ROL
(ID_ROL,DESCRIPCION,ES_JEFE,ACTIVO)
VALUES (1,'Administrador','S','S');

INSERT INTO ROL
(ID_ROL,DESCRIPCION,ES_JEFE,ACTIVO)
VALUES (2,'Almacenero','N','S');

INSERT INTO ROL
(ID_ROL,DESCRIPCION,ES_JEFE,ACTIVO)
VALUES (3,'Vendedor','N','S');

INSERT INTO ROL
(ID_ROL,DESCRIPCION,ES_JEFE,ACTIVO)
VALUES (4,'Jefe de Almacen','S','S');

INSERT INTO ROL
(ID_ROL,DESCRIPCION,ES_JEFE,ACTIVO)
VALUES (5,'Jefe de produccion','S','N');

-- Pregunta 11
SELECT ID_CLIENTE,RAZON_SOCIAL,TELEFONO,CORREO,DIRECCION_FISCAL
FROM CLIENTE
WHERE RUC IS NULL
ORDER BY 1;

-- Pregunta 12
SELECT DISTINCT C.ID_CLIENTE,C.RAZON_SOCIAL,C.RUC
FROM CLIENTE C, ORDENPEDIDO O
WHERE C.ID_CLIENTE=O.CLIENTE_ID_CLIENTE AND (C.RUC IS NULL OR C.DIRECCION_FISCAL LIKE 'Av%')
ORDER BY 1;

-- Pregunta 13
SELECT ID_SEDE,NOMBRESEDE,DISTRITO,PROVINCIA
FROM SEDE
WHERE AREA_SEDE>300 AND PROVINCIA='Lima' AND (DISTRITO='Villa El Salvador' OR DISTRITO='Lurin')
ORDER BY 1;