--ITEM a------------------------------------------------------------------------
SELECT S.IDSUPERVISOR,S.NOMBREVENDEDOR,COUNT(I.IDINMUEBLE) AS CANT_CONTRATOS
FROM EX1_VENDEDOR V,EX1_INMUEBLE I,
    (SELECT V.IDVENDEDOR AS IDSUPERVISOR,V.NOMBREVENDEDOR
        FROM EX1_VENDEDOR V
        WHERE V.IDSUPERVISOR IS NULL
    ) S
WHERE V.IDSUPERVISOR=S.IDSUPERVISOR AND V.IDVENDEDOR=I.IDVENDEDOR AND I.VENDIDO='1'
GROUP BY S.IDSUPERVISOR,S.NOMBREVENDEDOR
ORDER BY COUNT(I.IDINMUEBLE) DESC;

SELECT SUP.IDVENDEDOR, SUP.NOMBREVENDEDOR, COUNT(*) CANT_CONTRATOS
FROM EX1_VENDEDOR SUP, EX1_VENDEDOR VEN, EX1_INMUEBLE INM
WHERE VEN.IDSUPERVISOR = SUP.IDVENDEDOR 
    AND VEN.IDVENDEDOR = INM.IDVENDEDOR
    AND INM.VENDIDO = '1'
GROUP BY SUP.IDVENDEDOR, SUP.NOMBREVENDEDOR
ORDER BY 3 DESC;

--ITEM b------------------------------------------------------------------------
UPDATE EX1_VENDEDOR
SET IDSUPERVISOR=NULL
WHERE NOMBREVENDEDOR LIKE 'CALIXTO GARCIA, SUSAN';

INSERT INTO EX1_VENDEDOR
   (IDVENDEDOR, IDSUPERVISOR, NOMBREVENDEDOR, TELEFONO, EMAIL, EDAD, COMISION)
VALUES
   ('00000007', '00000003', 'SALAS RODRÍGUEZ, ALEX AUGUSTO', '99904587', 'asalasr@adn.com.pe', 30, 0.05);

INSERT INTO EX1_VENDEDOR
   (IDVENDEDOR, IDSUPERVISOR, NOMBREVENDEDOR, TELEFONO, EMAIL, EDAD, COMISION)
VALUES
   ('00000008', '00000003', 'CORTEZ OLIVEROS, PEDRO LUIS', '99799945', 'pcortezo@adn.com.pe', 29, 0.05);

--ITEM c------------------------------------------------------------------------
SELECT CLI.NOMBRE AS CLIENTE,SUM(CONT.PRECIO) AS TOTALCOMPRAS,
        CASE 
            WHEN SUM(CONT.PRECIO)>=60000 THEN 'A'
            WHEN SUM(CONT.PRECIO) BETWEEN 25000 AND 59999 THEN 'B'
            WHEN SUM(CONT.PRECIO)<=24999 THEN 'C'
        END AS CLASIFICACION
FROM EX1_CLIENTE CLI,EX1_CONTRATOVENTA CONT
WHERE CLI.IDCLIENTE=CONT.IDCLIENTE
GROUP BY CLI.NOMBRE
HAVING SUM(CONT.PRECIO)>=25000
ORDER BY CLASIFICACION,CLIENTE;


